version: '3'
services:
  proxy:
    labels:
      - traefik.enable=true
      - traefik.port=80
  backend:
    labels:
      - traefik.frontend.rule=PathPrefix:/api,/docs,/redoc
      - traefik.enable=true
      - traefik.port=80
      - traefik.tags=${TRAEFIK_TAG}