version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        env: dev
  backend-tests:
    build:
      context: ./backend
      dockerfile: tests.dockerfile
      args:
        env: dev